export const styles = {
  container: {
    display: 'flex',
    flexDirection: 'column',
    height: '100vh',
    background: 'var(--bg)',
    position: 'relative',
    zIndex: 1,
  },
  header: {
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'space-between',
    padding: '12px 24px',
    background: 'rgba(255,107,157,0.12)',
    borderBottom: '1px solid rgba(255,107,157,0.3)',
    backdropFilter: 'blur(10px)',
    flexShrink: 0,
  },
  headerTitle: {
    fontFamily: 'Fredoka One, cursive',
    fontSize: '1.4rem',
    background: 'linear-gradient(90deg, #FF6B9D, #C44DFF)',
    WebkitBackgroundClip: 'text',
    WebkitTextFillColor: 'transparent',
  },
  headerSub: {
    fontSize: '0.8rem',
    color: 'rgba(255,255,255,0.5)',
  },
  main: {
    display: 'flex',
    gap: '20px',
    padding: '20px',
    flex: 1,
    overflow: 'hidden',
  },
  cameraBox: {
    flex: 1,
    position: 'relative',
    borderRadius: '20px',
    overflow: 'hidden',
    background: '#0A0A16',
    border: '2px solid rgba(255,107,157,0.25)',
    boxShadow: '0 0 40px rgba(196,77,255,0.15)',
    minHeight: '300px',
  },
  hiddenVideo: {
    position: 'absolute',
    opacity: 0,
    width: 1,
    height: 1,
  },
  canvas: {
    width: '100%',
    height: '100%',
    objectFit: 'cover',
    display: 'block',
    transform: 'none',
  },
  cameraOverlay: {
    position: 'absolute',
    inset: 0,
    display: 'flex',
    flexDirection: 'column',
    alignItems: 'center',
    justifyContent: 'center',
    gap: '12px',
  },
  cameraIconBig: {
    fontSize: '4rem',
  },
  cameraOverlayText: {
    color: 'rgba(255,255,255,0.4)',
    fontSize: '1rem',
  },
  progressBarWrapper: {
    position: 'absolute',
    bottom: 0,
    left: 0,
    right: 0,
    height: '6px',
    background: 'rgba(255,255,255,0.1)',
  },
  progressBar: {
    height: '100%',
    background: 'linear-gradient(90deg, #FF6B9D, #C44DFF)',
    transition: 'width 0.1s ease',
    borderRadius: '3px',
  },
  statusBadge: {
    position: 'absolute',
    bottom: '16px',
    left: '50%',
    transform: 'translateX(-50%)',
    background: 'rgba(0,0,0,0.7)',
    backdropFilter: 'blur(8px)',
    padding: '8px 20px',
    borderRadius: '30px',
    fontSize: '0.82rem',
    color: '#fff',
    border: '1px solid rgba(255,107,157,0.3)',
    whiteSpace: 'nowrap',
  },
  debugRow: {
    position: 'absolute',
    top: '12px',
    left: '12px',
    display: 'flex',
    gap: '8px',
  },
  debugBadge: {
    padding: '4px 12px',
    borderRadius: '20px',
    fontSize: '0.72rem',
    fontWeight: '700',
    transition: 'background 0.2s ease',
  },
  sidePanel: {
    width: '260px',
    display: 'flex',
    flexDirection: 'column',
    gap: '14px',
    flexShrink: 0,
  },
  instructionCard: {
    background: 'rgba(255,255,255,0.05)',
    borderRadius: '16px',
    padding: '16px',
    border: '1px solid rgba(255,107,157,0.2)',
  },
  instructionTitle: {
    fontFamily: 'Fredoka One, cursive',
    color: '#FF6B9D',
    marginBottom: '10px',
    fontSize: '1rem',
  },
  instructionList: {
    paddingLeft: '18px',
    fontSize: '0.82rem',
    color: 'rgba(255,255,255,0.8)',
    lineHeight: '1.8',
  },
  musicCard: {
    background: 'rgba(255,255,255,0.05)',
    borderRadius: '16px',
    padding: '16px',
    border: '1px solid rgba(196,77,255,0.2)',
  },
  musicTitle: {
    fontFamily: 'Fredoka One, cursive',
    color: '#C44DFF',
    marginBottom: '8px',
    fontSize: '1rem',
  },
  musicDesc: {
    fontSize: '0.78rem',
    color: 'rgba(255,255,255,0.6)',
    lineHeight: 1.6,
    marginBottom: '8px',
  },
  code: {
    background: 'rgba(196,77,255,0.2)',
    padding: '1px 5px',
    borderRadius: '4px',
    fontFamily: 'monospace',
    fontSize: '0.8rem',
    color: '#C44DFF',
  },
  musicActive: {
    fontSize: '0.78rem',
    color: '#4DFFEE',
  },
  musicInactive: {
    fontSize: '0.78rem',
    color: '#FFE66D',
  },
  btn: {
    padding: '14px',
    border: 'none',
    borderRadius: '14px',
    color: 'white',
    fontFamily: 'Fredoka One, cursive',
    fontSize: '1rem',
    cursor: 'pointer',
    transition: 'transform 0.15s, opacity 0.2s',
    letterSpacing: '0.5px',
    boxShadow: '0 4px 20px rgba(255,107,157,0.3)',
    marginTop: 'auto',
  },
  catOverlay: {
    position: 'fixed',
    inset: 0,
    background: 'rgba(0,0,0,0.85)',
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'center',
    zIndex: 1000,
    backdropFilter: 'blur(6px)',
    cursor: 'pointer',
    animation: 'fadeIn 0.3s ease',
  },
  catContainer: {
    display: 'flex',
    flexDirection: 'column',
    alignItems: 'center',
    gap: '16px',
    position: 'relative',
  },
  catEmoji: {
    fontSize: '3rem',
    animation: 'bounce 0.5s ease infinite alternate',
  },
  catGif: {
    width: '280px',
    height: '280px',
    objectFit: 'contain',
    borderRadius: '20px',
    border: '4px solid #FF6B9D',
    boxShadow: '0 0 60px rgba(255,107,157,0.6)',
  },
  catText: {
    fontFamily: 'Fredoka One, cursive',
    fontSize: '2.5rem',
    background: 'linear-gradient(90deg, #FF6B9D, #FFE66D, #C44DFF)',
    WebkitBackgroundClip: 'text',
    WebkitTextFillColor: 'transparent',
    animation: 'pulse 0.6s ease infinite alternate',
  },
  catSubText: {
    color: 'rgba(255,255,255,0.4)',
    fontSize: '0.8rem',
  },
  sparkle: {
    position: 'absolute',
    fontSize: '1.5rem',
    animation: 'sparkleAnim 1s ease infinite alternate',
  },
};
